# This is actually slower because of the enormous size.
#cache:
#  key: nitrogen
#  paths:
#    - target/

before_script:
  - whoami
  - groups
  - nix-shell --run "rustc --version"

check_format:
  tags:
    - rust
    - nix
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - nix-shell --run "cargo fmt --all -- --check"

check_clippy:
  interruptible: true
  tags:
    - rust
    - nix
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - nix-shell --run "cargo clippy --all --all-targets -- --deny warnings"

check_test:
  interruptible: true
  tags:
    - rust
    - nix
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - nix-shell --run "cargo test --workspace --all-targets --no-fail-fast"
  retry: 2 # Sometimes X clients just crash

build_release_linux_x64:
  interruptible: true
  tags:
    - rust
    - nix
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
  allow_failure: true
  script:
    - export VERSION=$(date +%Y.%m.%d.%H.%M)
    - export PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/nitrogen/${VERSION}"
    - export PACKAGE_LINUX_X64="nitrogen-linux-x86_64.tar.xz"
    - export PACKAGE_WINDOWS_X64="nitrogen-win-x86_64.exe.xz"
    - nix-shell --run "cargo build --release --all"
    - mkdir "nitrogen-$VERSION"
    - cp target/release/nitrogen "nitrogen-$VERSION"/
    - tar -C "nitrogen-$VERSION/" -cJvf "../${PACKAGE_LINUX_X64}" .
    - mv "../${PACKAGE_LINUX_X64}" .
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${PACKAGE_LINUX_X64} "${PACKAGE_REGISTRY_URL}/${PACKAGE_LINUX_X64}"'
    - |
      /etc/nixos/release-cli create --name "Release $VERSION" --tag-name $VERSION \
        --assets-link "{\"name\":\"${PACKAGE_LINUX_X64}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_LINUX_X64}\"}"

# If we ever want to release all our misc binaries, this will do it.
#    - find target/release/ -maxdepth 1 -type f -executable -not -iname "*.so" -exec cp \{\} "nitrogen-$CI_COMMIT_TIMESTAMP" \;

# If we ever build and release windows binaries, this line will add the asset link
#       --assets-link "{\"name\":\"${PACKAGE_WINDOWS_X64}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_WINDOWS_X64}\"}"
