cache:
  key: nitrogen
  paths:
    - target/
    - libs/**/**/target/

before_script:
  - whoami
  - groups
  - nix-shell --run "rustc --version"
  #- rustup target add x86_64-pc-windows-gnu

check_format:
  tags:
    - rust
    - nix
  script:
    - nix-shell --run "cargo fmt --all -- --check"

check_clippy:
  interruptible: true
  tags:
    - rust
    - nix
  script:
    - nix-shell --run "cargo clippy --all --all-targets -- --deny warnings"

check_test:
  interruptible: true
  tags:
    - rust
    - nix
  script:
    - nix-shell --run "cargo test --workspace --all-targets --no-fail-fast"
  retry: 2 # Sometimes X clients just crash

build_release_linux_x64:
#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME != $CI_DEFAULT_BRANCH'
#      when: never
  interruptible: true
  tags:
    - rust
    - nix
  script:
    - nix-shell --run "cargo build --release --all"
    - xz --compress target/release/nitrogen
    #- 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "../nitrogen-${CI_COMMIT_TIMESTAMP}.tar.xz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/nitrogen/${CI_COMMIT_TIMESTAMP}/nitrogen-bin.tar.xz"'
    #- mkdir "nitrogen-$CI_COMMIT_TIMESTAMP"
    #- find target/release/ -maxdepth 1 -type f -executable -not -iname "*.so" -exec cp \{\} "nitrogen-$CI_COMMIT_TIMESTAMP" \;
    #- tar -C "nitrogen-$CI_COMMIT_TIMESTAMP/" -cJvf "../nitrogen-${CI_COMMIT_TIMESTAMP}.tar.xz" .

#  release:
#    tag_name: $CI_COMMIT_TIMESTAMP
#    description: $CI_COMMIT_MESSAGE
#    assets:
#      links:
