# This is actually slower because of the enormous size.
#cache:
#  key: nitrogen
#  paths:
#    - target/

before_script:
  - whoami
  - groups
  - nix-shell --run "rustc --version"
  #- rustup target add x86_64-pc-windows-gnu

check_format:
  tags:
    - rust
    - nix
  script:
    - nix-shell --run "cargo fmt --all -- --check"

check_clippy:
  interruptible: true
  tags:
    - rust
    - nix
  script:
    - nix-shell --run "cargo clippy --all --all-targets -- --deny warnings"

check_test:
  interruptible: true
  tags:
    - rust
    - nix
  script:
    - nix-shell --run "cargo test --workspace --all-targets --no-fail-fast"
  retry: 2 # Sometimes X clients just crash

build_release_linux_x64:
#  rules:
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME != $CI_DEFAULT_BRANCH'
#      when: never
  interruptible: true
  tags:
    - rust
    - nix
  script:
    - export VERSION=$(date +%Y.%m.%d.%H.%M)
    - export PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/nitrogen/${VERSION}"
    - export PACKAGE_LINUX_X64="nitrogen-linux-x86_64.tar.xz"
    - export PACKAGE_WINDOWS_X64="nitrogen-win-x86_64.exe.xz"
    - nix-shell --run "cargo build --release --all"
    - mkdir "nitrogen-$VERSION"
    - cp target/release/nitrogen "nitrogen-$VERSION"/
    - tar -C "nitrogen-$VERSION/" -cJvf "../${PACKAGE_LINUX_X64}" .
    - mv "../${PACKAGE_LINUX_X64}" .
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${PACKAGE_LINUX_X64} "${PACKAGE_REGISTRY_URL}/${PACKAGE_LINUX_X64}"'
    - |
      /etc/nixos/release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${PACKAGE_LINUX_X64}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_LINUX_X64}\"}" \
        --assets-link "{\"name\":\"${PACKAGE_WINDOWS_X64}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_WINDOWS_X64}\"}"

#    - find target/release/ -maxdepth 1 -type f -executable -not -iname "*.so" -exec cp \{\} "nitrogen-$CI_COMMIT_TIMESTAMP" \;
#  release:
#    tag_name: $CI_COMMIT_TIMESTAMP
#    description: $CI_COMMIT_MESSAGE
#    assets:
#      links:
#        - name: "${PACKAGE_LINUX_X64}"
#          url: "${PACKAGE_REGISTRY_URL}/${PACKAGE_LINUX_X64}"
