cache:
  paths:
    - target/
    - libs/**/**/target/

before_script:
  - whoami
  - groups
  - nix-shell --run "rustc --version"
  #- rustup target add x86_64-pc-windows-gnu

check_format:
  tags:
    - rust
    - nix
  script:
    - nix-shell --run "cargo fmt --all -- --check"

check_clippy:
  tags:
    - rust
    - nix
  script:
    - nix-shell --run "cargo clippy --all --all-targets -- --deny warnings"

check_test:
  tags:
    - rust
    - nix
  script:
    - nix-shell --run "cargo test --all --all-targets"
