#cache:
#  paths:
#    - target/
#    - libs/**/**/target/

before_script:
  - whoami
  - groups
  - which rustup
  - rustup update
  - rustup target add x86_64-pc-windows-gnu
  - rustup component add rustfmt

check_format:
  tags:
    - rust
  script:
    - cargo fmt --all -- --check

check_clippy:
  tags:
    - rust
    - nix
  script:
    - nix-shell -p gnumake gmock --run "cargo clippy --all --all-targets -- --deny warnings"
    #- nix-shell -p pkgconfig xorg.libX11 --run "cargo clippy --all --all-targets -- --deny warnings"

# Need to figure out how to run graphical tests headless.
#check_build:
#  script:
#    - cargo check --all --all-targets
#

check_test:
  tags:
    - rust
    - nix
  script:
    - nix-shell -p gnumake gmock --run "cargo test --all --all-targets"
