[package]
name = "nitrogen"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "apps/dump-terrain-tables",

    "libs/sim/absolute_unit",
    "libs/sim/camera",
    "libs/sim/geodesy",
    "libs/sim/geometry",
    "libs/sim/orrery",
    "libs/sim/physical_constants",
    "libs/sim/star_catalog",

    "libs/system/ansi",
    "libs/system/command",
    "libs/system/frame_graph",
    "libs/system/gpu",
    "libs/system/input",
    "libs/system/packed_struct",

    "libs/wgpu-buffer/atmosphere",
    "libs/wgpu-buffer/font_common",
    "libs/wgpu-buffer/font_ttf",
    "libs/wgpu-buffer/fullscreen",
    "libs/wgpu-buffer/global_data",
    "libs/wgpu-buffer/text_layout",

    "libs/wgpu-render/build-shaders",
    "libs/wgpu-render/shader_shared",
    "libs/wgpu-render/screen_text",
]

[dependencies]
