[package]
name = "nitrogen"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "apps/dump-layer-pack",
    "apps/dump-terrain-tables",
    "apps/dump-terrain-tiles",

    "libs/sim/absolute_unit",
    "libs/sim/animate",
    "libs/sim/camera",
    "libs/sim/geodesy",
    "libs/sim/geometry",
    "libs/sim/orrery",
    "libs/sim/physical_constants",
    "libs/sim/star_catalog",
    "libs/sim/universe",

    "libs/system/ansi",
    "libs/system/catalog",
    "libs/system/command",
    "libs/system/commandable",
    "libs/system/gpu",
    "libs/system/input",
    "libs/system/packed_struct",

    "libs/wgpu-buffer/atmosphere",
    "libs/wgpu-buffer/font_common",
    "libs/wgpu-buffer/font_ttf",
    "libs/wgpu-buffer/fullscreen",
    "libs/wgpu-buffer/global_data",
    "libs/wgpu-buffer/stars",
    "libs/wgpu-buffer/terrain_geo",
    "libs/wgpu-buffer/text_layout",

    "libs/wgpu-render/build-shaders",
    "libs/wgpu-render/shader_shared",
    "libs/wgpu-render/screen_text",
    "libs/wgpu-render/skybox",
    "libs/wgpu-render/terrain",
]

[dependencies]
chrono = "^ 0.4"
env_logger = "^ 0.7"
failure = "^ 0.1.2"
image = "^ 0.21"
legion = "= 0.2.4"
log = "^ 0.4"
nalgebra = "^ 0.20"
structopt = "^ 0.2"
tokio = { version = "^ 0.2", features = ["rt-threaded", "macros", "fs", "sync"] }
absolute_unit = { path = "libs/sim/absolute_unit" }
atmosphere = { path = "libs/wgpu-buffer/atmosphere" }
camera = { path = "libs/sim/camera" }
catalog = { path = "libs/system/catalog" }
command = { path = "libs/system/command" }
fullscreen = { path = "libs/wgpu-buffer/fullscreen" }
geodesy = { path = "libs/sim/geodesy" }
global_data = { path = "libs/wgpu-buffer/global_data" }
gpu = { path = "libs/system/gpu" }
input = { path = "libs/system/input" }
orrery = { path = "libs/sim/orrery" }
screen_text = { path = "libs/wgpu-render/screen_text" }
skybox = { path = "libs/wgpu-render/skybox" }
stars = { path = "libs/wgpu-buffer/stars" }
terrain = { path = "libs/wgpu-render/terrain" }
terrain_geo = { path = "libs/wgpu-buffer/terrain_geo" }
text_layout = { path = "libs/wgpu-buffer/text_layout" }
universe = { path = "libs/sim/universe" }
