[package]
name = "nitrogen"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "apps/dump-layer-pack",
    "apps/dump-terrain-tables",
    "apps/dump-terrain-tiles",
    "apps/web-demo",

    "libs/sim/absolute_unit",
    "libs/sim/animate",
    "libs/sim/camera",
    "libs/sim/geodesy",
    "libs/sim/geometry",
    "libs/sim/orrery",
    "libs/sim/physical_constants",
    "libs/sim/star_catalog",
    "libs/sim/universe",

    "libs/system/ansi",
    "libs/system/build_shaders",
    "libs/system/catalog",
    "libs/system/gpu",
    "libs/system/input",
    "libs/system/nitrous",
    "libs/system/nitrous_injector",
    "libs/system/packed_struct",

    "libs/wgpu-buffer/atlas",
    "libs/wgpu-buffer/atmosphere",
    "libs/wgpu-buffer/composite",
    "libs/wgpu-buffer/font_common",
    "libs/wgpu-buffer/font_ttf",
    "libs/wgpu-buffer/fullscreen",
    "libs/wgpu-buffer/global_data",
    "libs/wgpu-buffer/shader_shared",
    "libs/wgpu-buffer/stars",
    "libs/wgpu-buffer/terrain_geo",
    "libs/wgpu-buffer/ui",
    "libs/wgpu-buffer/widget",
    "libs/wgpu-buffer/world",
]

[dependencies]
chrono = "^ 0.4"
env_logger = "^ 0.8"
anyhow = "^ 1"
image = "^ 0.23"
legion = "^ 0.3"
log = "^ 0.4"
nalgebra = "^ 0.24"
parking_lot = "^ 0.11"
paste = "^ 1"
structopt = "^ 0.3"
tokio = { version = "^ 1.0", features = ["rt-multi-thread", "macros", "io-util", "fs", "sync"] }
winit = { version = "^ 0.24", features = ["web-sys"] }
absolute_unit = { path = "libs/sim/absolute_unit" }
atmosphere = { path = "libs/wgpu-buffer/atmosphere" }
camera = { path = "libs/sim/camera" }
catalog = { path = "libs/system/catalog" }
composite = { path = "libs/wgpu-buffer/composite" }
fullscreen = { path = "libs/wgpu-buffer/fullscreen" }
geodesy = { path = "libs/sim/geodesy" }
global_data = { path = "libs/wgpu-buffer/global_data" }
gpu = { path = "libs/system/gpu" }
input = { path = "libs/system/input" }
nitrous = { path = "libs/system/nitrous" }
nitrous_injector = { path = "libs/system/nitrous_injector" }
orrery = { path = "libs/sim/orrery" }
stars = { path = "libs/wgpu-buffer/stars" }
terrain_geo = { path = "libs/wgpu-buffer/terrain_geo" }
ui = { path = "libs/wgpu-buffer/ui" }
universe = { path = "libs/sim/universe" }
widget = { path = "libs/wgpu-buffer/widget" }
world = { path = "libs/wgpu-buffer/world" }
