[package]
name = "web-demo"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
approx = "^ 0.3"
console_error_panic_hook = "^ 0.1"
failure = "^ 0.1.2"
legion = "= 0.2.4"
log = "^ 0.4"
smallvec = "^ 1.4"
tokio = { version = "^ 1.0", features = ["rt-multi-thread", "macros", "io-util", "fs", "sync"] }
wasm-bindgen = "^ 0.2"
wasm-bindgen-futures = "^ 0.4"
web-sys = "=0.3.39"
wgpu = "^ 0.6"
winit = { version = "^ 0.24", features = ["web-sys"] }
absolute_unit = { path = "../../libs/sim/absolute_unit" }
camera = { path = "../../libs/sim/camera" }
command = { path = "../../libs/system/command" }
fullscreen = { path = "../../libs/wgpu-buffer/fullscreen" }
geodesy = { path = "../../libs/sim/geodesy" }
global_data = { path = "../../libs/wgpu-buffer/global_data" }
gpu = { path = "../../libs/system/gpu" }
input = { path = "../../libs/system/input" }
