[package]
name = "web-demo"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
approx = "^ 0.3"
failure = "^ 0.1.2"
log = "^ 0.4"
smallvec = "^ 0.6"
wasm-bindgen = "0.2.68"
web-sys = "^ 0.3"
winit = { version = "^ 0.23", features = ["web-sys"] }
command = { path = "../../libs/system/command" }
input = { path = "../../libs/system/input" }
