[package]
name = "dump-layer-pack"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "^ 1"
memmap = "^ 0.7"
structopt = "^ 0.3"
zerocopy = "^ 0.5"
terrain = { path = "../../libs/wgpu-buffer/terrain" }
